package com.malik.alshurti.remote

import android.content.Context
import android.media.AudioAttributes
import android.media.MediaPlayer
import android.os.Handler
import android.os.Looper
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.cancel
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import org.json.JSONObject
import java.io.File
import java.io.FileOutputStream
import java.net.HttpURLConnection
import java.net.URL
import java.util.concurrent.atomic.AtomicLong

/** High-quality Arabic voice generated by Chatterbox Multilingual V3 on the backend. */
class RemoteArabicVoice(
    context: Context,
    private val callbacks: Callbacks
) {
    interface Callbacks {
        fun onPreparing(percent: Int, message: String)
        fun onReady()
        fun onSpeechStarted(durationMs: Long)
        fun onSpeechCursor(fraction: Float)
        fun onSpeechFinished()
        fun onError(message: String)
    }

    private val appContext = context.applicationContext
    private val locator = BackendLocator(appContext)
    private val scope = CoroutineScope(SupervisorJob() + Dispatchers.IO)
    private val main = Handler(Looper.getMainLooper())
    private val generation = AtomicLong(0L)

    @Volatile private var released = false
    @Volatile private var ready = false
    @Volatile private var baseUrl: String? = null
    @Volatile private var player: MediaPlayer? = null
    private var cursorJob: Job? = null

    fun prepare() {
        if (released) return
        if (ready && baseUrl != null) {
            callbacks.onReady()
            return
        }

        callbacks.onPreparing(15, "جاري الاتصال بصوت الشرطي…")
        scope.launch {
            try {
                val url = locator.resolve()
                baseUrl = url
                ready = true
                main.post {
                    callbacks.onPreparing(100, "صوت الشرطي جاهز")
                    callbacks.onReady()
                }
            } catch (t: Throwable) {
                ready = false
                main.post { callbacks.onError(t.message ?: "تعذر الاتصال بخادم الصوت الحقيقي.") }
            }
        }
    }

    fun speak(
        text: String,
        voiceProfile: String = "police",
        exaggeration: Float? = null
    ) {
        val clean = text.trim()
        if (clean.isBlank()) {
            callbacks.onSpeechFinished()
            return
        }
        val url = baseUrl
        if (!ready || url == null) {
            callbacks.onError("خادم الصوت غير جاهز.")
            return
        }

        val ticket = generation.incrementAndGet()
        stopPlayer()
        callbacks.onPreparing(20, "جاري تجهيز الصوت…")

        scope.launch {
            var connection: HttpURLConnection? = null
            var file: File? = null
            try {
                connection = (URL("$url/v1/tts").openConnection() as HttpURLConnection).apply {
                    connectTimeout = 5_000
                    readTimeout = 90_000
                    requestMethod = "POST"
                    doOutput = true
                    setRequestProperty("Content-Type", "application/json; charset=utf-8")
                    setRequestProperty("Accept", "audio/wav")
                }
                val body = JSONObject()
                    .put("text", clean.take(500))
                    .put("voice", voiceProfile)
                    .apply { if (exaggeration != null) put("exaggeration", exaggeration) }
                    .toString()
                    .toByteArray(Charsets.UTF_8)
                connection.outputStream.use { it.write(body) }

                val code = connection.responseCode
                if (code !in 200..299) {
                    val detail = connection.errorStream?.bufferedReader()?.use { it.readText() }.orEmpty()
                    error("تعذر توليد الصوت الحقيقي ($code)${if (detail.isNotBlank()) ": ${detail.take(120)}" else ""}")
                }

                file = File.createTempFile("alshorti-chatterbox-", ".wav", appContext.cacheDir)
                connection.inputStream.use { input ->
                    FileOutputStream(file).use { output -> input.copyTo(output, 128 * 1024) }
                }
                check(file.length() > 4_096) { "خادم الصوت رجع ملف صوت غير صالح." }
                if (ticket != generation.get() || released) {
                    file.delete()
                    return@launch
                }

                val readyFile = file
                main.post {
                    callbacks.onPreparing(95, "تم تجهيز الصوت")
                    play(ticket, readyFile)
                }
            } catch (t: Throwable) {
                file?.delete()
                ready = false
                locator.invalidate()
                if (ticket == generation.get() && !released) {
                    main.post { callbacks.onError(t.message ?: "تعذر تشغيل الصوت الحقيقي.") }
                }
            } finally {
                connection?.disconnect()
            }
        }
    }

    fun interrupt() {
        generation.incrementAndGet()
        main.post { stopPlayer() }
    }

    fun release() {
        released = true
        generation.incrementAndGet()
        main.post { stopPlayer() }
        scope.cancel()
    }

    private fun play(ticket: Long, file: File) {
        if (ticket != generation.get() || released) {
            file.delete()
            return
        }
        stopPlayer()

        val active = MediaPlayer().apply {
            setAudioAttributes(
                AudioAttributes.Builder()
                    .setUsage(AudioAttributes.USAGE_ASSISTANT)
                    .setContentType(AudioAttributes.CONTENT_TYPE_SPEECH)
                    .build()
            )
            setDataSource(file.absolutePath)
            setOnPreparedListener { prepared ->
                if (ticket != generation.get() || released) {
                    runCatching { prepared.release() }
                    file.delete()
                    return@setOnPreparedListener
                }
                val duration = prepared.duration.coerceAtLeast(1)
                callbacks.onSpeechStarted(duration.toLong())
                prepared.start()
                startCursor(ticket, prepared, duration)
            }
            setOnCompletionListener { completed ->
                if (player === completed) player = null
                cursorJob?.cancel()
                cursorJob = null
                runCatching { completed.release() }
                file.delete()
                if (ticket == generation.get() && !released) callbacks.onSpeechFinished()
            }
            setOnErrorListener { failed, _, _ ->
                if (player === failed) player = null
                cursorJob?.cancel()
                cursorJob = null
                runCatching { failed.release() }
                file.delete()
                if (ticket == generation.get() && !released) callbacks.onError("تعذر تشغيل ملف الصوت الحقيقي.")
                true
            }
        }
        player = active
        active.prepareAsync()
    }

    private fun startCursor(ticket: Long, active: MediaPlayer, durationMs: Int) {
        cursorJob?.cancel()
        cursorJob = scope.launch(Dispatchers.Main) {
            while (ticket == generation.get() && player === active && !released) {
                val position = runCatching { active.currentPosition }.getOrDefault(0)
                callbacks.onSpeechCursor((position.toFloat() / durationMs).coerceIn(0f, 1f))
                delay(55)
            }
        }
    }

    private fun stopPlayer() {
        cursorJob?.cancel()
        cursorJob = null
        val active = player ?: return
        player = null
        runCatching { active.stop() }
        runCatching { active.reset() }
        runCatching { active.release() }
    }
}
