package com.malik.alshurti

import org.apache.commons.compress.compressors.bzip2.BZip2CompressorInputStream
import java.io.EOFException
import java.io.File
import java.io.InputStream
import java.io.RandomAccessFile
import kotlin.math.max
import kotlin.math.min

/**
 * Streaming BSDIFF40 patch applier.
 *
 * The installed APK is read directly from ApplicationInfo.sourceDir, the patch is streamed from
 * disk and the target APK is written sequentially. No full APK is held in RAM. The format matches
 * bsdiff4/standard BSDIFF40 generated by the release workflow.
 */
object BsDiffPatch {
    private const val HEADER_SIZE = 32L
    private const val BUFFER_SIZE = 128 * 1024
    private val MAGIC = "BSDIFF40".toByteArray(Charsets.US_ASCII)

    fun apply(oldFile: File, patchFile: File, newFile: File) {
        require(oldFile.isFile && oldFile.length() > 0L) { "Source APK is missing." }
        require(patchFile.isFile && patchFile.length() >= HEADER_SIZE) { "Delta patch is invalid." }

        RandomAccessFile(patchFile, "r").use { headerFile ->
            val magic = ByteArray(8)
            headerFile.readFully(magic)
            require(magic.contentEquals(MAGIC)) { "Unsupported delta patch format." }

            val controlLength = readOffset(headerFile)
            val diffLength = readOffset(headerFile)
            val newSize = readOffset(headerFile)

            require(controlLength >= 0L && diffLength >= 0L && newSize >= 0L) {
                "Delta patch header is invalid."
            }
            val controlOffset = HEADER_SIZE
            val diffOffset = controlOffset + controlLength
            val extraOffset = diffOffset + diffLength
            require(extraOffset in HEADER_SIZE..patchFile.length()) { "Delta patch is truncated." }

            SliceInputStream(patchFile, controlOffset, controlLength).use { controlSlice ->
                SliceInputStream(patchFile, diffOffset, diffLength).use { diffSlice ->
                    SliceInputStream(patchFile, extraOffset, patchFile.length() - extraOffset).use { extraSlice ->
                        BZip2CompressorInputStream(controlSlice, true).use { control ->
                            BZip2CompressorInputStream(diffSlice, true).use { diff ->
                                BZip2CompressorInputStream(extraSlice, true).use { extra ->
                                    applyStreams(oldFile, newFile, newSize, control, diff, extra)
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    private fun applyStreams(
        oldFile: File,
        newFile: File,
        newSize: Long,
        control: InputStream,
        diff: InputStream,
        extra: InputStream
    ) {
        newFile.parentFile?.mkdirs()
        if (newFile.exists()) newFile.delete()

        RandomAccessFile(oldFile, "r").use { old ->
            RandomAccessFile(newFile, "rw").use { output ->
                var oldPosition = 0L
                var newPosition = 0L
                val diffBuffer = ByteArray(BUFFER_SIZE)
                val oldBuffer = ByteArray(BUFFER_SIZE)

                while (newPosition < newSize) {
                    val addLength = readOffset(control)
                    val extraLength = readOffset(control)
                    val seekDelta = readOffset(control)
                    require(addLength >= 0L && extraLength >= 0L) { "Delta control block is invalid." }
                    require(newPosition + addLength <= newSize) { "Delta writes beyond target APK." }

                    var processed = 0L
                    while (processed < addLength) {
                        val count = min(BUFFER_SIZE.toLong(), addLength - processed).toInt()
                        readFully(diff, diffBuffer, count)

                        val absoluteOldStart = oldPosition + processed
                        val validStart = max(0L, -absoluteOldStart).coerceAtMost(count.toLong()).toInt()
                        val validEnd = min(
                            count.toLong(),
                            old.length() - absoluteOldStart
                        ).coerceAtLeast(validStart.toLong()).toInt()

                        if (validEnd > validStart) {
                            val validCount = validEnd - validStart
                            old.seek(absoluteOldStart + validStart)
                            old.readFully(oldBuffer, validStart, validCount)
                            for (index in validStart until validEnd) {
                                diffBuffer[index] = (
                                    (diffBuffer[index].toInt() and 0xff) +
                                        (oldBuffer[index].toInt() and 0xff)
                                    ).toByte()
                            }
                        }

                        output.write(diffBuffer, 0, count)
                        processed += count
                    }
                    newPosition += addLength
                    oldPosition += addLength

                    require(newPosition + extraLength <= newSize) { "Delta extra block exceeds target APK." }
                    copyExact(extra, output, extraLength)
                    newPosition += extraLength
                    oldPosition += seekDelta
                }

                require(newPosition == newSize) { "Delta target size mismatch." }
                output.fd.sync()
            }
        }
    }

    private fun copyExact(input: InputStream, output: RandomAccessFile, byteCount: Long) {
        val buffer = ByteArray(BUFFER_SIZE)
        var remaining = byteCount
        while (remaining > 0L) {
            val count = min(buffer.size.toLong(), remaining).toInt()
            readFully(input, buffer, count)
            output.write(buffer, 0, count)
            remaining -= count
        }
    }

    private fun readOffset(input: InputStream): Long {
        val buffer = ByteArray(8)
        readFully(input, buffer, buffer.size)
        return decodeOffset(buffer)
    }

    private fun readOffset(file: RandomAccessFile): Long {
        val buffer = ByteArray(8)
        file.readFully(buffer)
        return decodeOffset(buffer)
    }

    /** Original BSDIFF signed-magnitude little-endian 64-bit integer. */
    private fun decodeOffset(buffer: ByteArray): Long {
        var value = (buffer[7].toInt() and 0x7f).toLong()
        for (index in 6 downTo 0) {
            value = value * 256L + (buffer[index].toInt() and 0xff)
        }
        return if ((buffer[7].toInt() and 0x80) != 0) -value else value
    }

    private fun readFully(input: InputStream, buffer: ByteArray, count: Int) {
        var offset = 0
        while (offset < count) {
            val read = input.read(buffer, offset, count - offset)
            if (read < 0) throw EOFException("Unexpected end of delta patch.")
            offset += read
        }
    }

    private class SliceInputStream(
        file: File,
        offset: Long,
        private val length: Long
    ) : InputStream() {
        private val random = RandomAccessFile(file, "r").apply { seek(offset) }
        private var position = 0L

        override fun read(): Int {
            if (position >= length) return -1
            val value = random.read()
            if (value >= 0) position += 1L
            return value
        }

        override fun read(buffer: ByteArray, offset: Int, length: Int): Int {
            if (position >= this.length) return -1
            val allowed = min(length.toLong(), this.length - position).toInt()
            val read = random.read(buffer, offset, allowed)
            if (read > 0) position += read.toLong()
            return read
        }

        override fun close() {
            random.close()
        }
    }
}
